"""
report_generator.py
────────────────────
Generates a printable PDF screening report using fpdf2.
Suitable for sharing with mental health providers.
"""

import time
from io import BytesIO
from datetime import datetime
from typing import Optional

from modules.screening_engine import ScreeningResult


def generate_pdf_report(
    result: ScreeningResult,
    patient_name: str = "Anonymous",
    dob: str = "Not provided",
    clinician: str = "Not specified",
) -> bytes:
    """Return PDF bytes for the screening report."""
    try:
        from fpdf import FPDF
    except ImportError:
        return b""

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    # ── Header ─────────────────────────────────────────────────────────
    pdf.set_fill_color(26, 38, 64)
    pdf.rect(0, 0, 210, 28, "F")
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_xy(10, 6)
    pdf.cell(0, 8, "bpdisdet  |  Multimodal Mental Health Screening Report", ln=True)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_x(10)
    pdf.cell(0, 6, "Bipolar Disorder Detection System  |  For Clinical Review Only  |  Not a Diagnosis", ln=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(6)

    # ── Disclaimer ──────────────────────────────────────────────────────
    pdf.set_fill_color(255, 243, 205)
    pdf.set_draw_color(230, 170, 30)
    pdf.set_font("Helvetica", "B", 9)
    pdf.set_x(10)
    pdf.multi_cell(190, 5,
        "⚠  DISCLAIMER: This report is generated by an AI-assisted screening tool and does NOT constitute "
        "a clinical diagnosis. Results must be reviewed and interpreted by a licensed mental health "
        "professional. This tool is designed to support — not replace — clinical judgment.",
        border=1, fill=True)
    pdf.ln(5)

    # ── Patient Info ────────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Patient & Session Information", ln=True)
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    info = [
        ("Patient Name", patient_name),
        ("Date of Birth", dob),
        ("Referring Clinician", clinician),
        ("Session ID", result.session_id),
        ("Report Generated", datetime.fromtimestamp(result.timestamp).strftime("%Y-%m-%d %H:%M:%S")),
        ("Modalities Used",
         ("Facial + Text" if result.has_facial_data and result.has_text_data
          else "Text Only" if result.has_text_data else "Facial Only")),
    ]
    pdf.set_font("Helvetica", "", 10)
    for label, value in info:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_x(10)
        pdf.cell(55, 6, f"{label}:")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 6, str(value), ln=True)
    pdf.ln(4)

    # ── Risk Banner ──────────────────────────────────────────────────────
    RISK_RGB = {
        "high": (224, 82, 82),
        "moderate": (224, 154, 47),
        "low": (76, 175, 125),
        "minimal": (91, 155, 213),
    }
    r, g, b = RISK_RGB.get(result.overall_risk, (150, 150, 150))
    pdf.set_fill_color(r, g, b)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_x(10)
    pdf.cell(190, 10,
             f"  OVERALL RISK LEVEL: {result.overall_risk.upper()}   |   "
             f"DOMINANT STATE: {result.dominant_state.upper()}",
             ln=True, fill=True, align="C")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # ── Composite Scores ────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Composite Screening Scores", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    scores = [
        ("Mania Index",             result.composite_mania_score),
        ("Depression Index",        result.composite_depression_score),
        ("Mixed State Index",       result.composite_mixed_score),
        ("Affective Instability",   result.affective_instability_index),
    ]
    for label, score in scores:
        _draw_score_bar(pdf, label, score)
    pdf.ln(2)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 5, f"Screening Confidence: {result.confidence_pct:.0f}%  (max 85% — screening tool limitation)", ln=True)
    pdf.ln(4)

    # ── Clinical Summary ────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Clinical Summary", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    # Strip markdown bold markers for PDF
    import re
    clean_summary = re.sub(r"\*\*(.*?)\*\*", r"\1", result.clinical_summary)
    pdf.set_x(10)
    pdf.multi_cell(190, 6, clean_summary)
    pdf.ln(4)

    # ── Red Flags ────────────────────────────────────────────────────────
    if result.red_flags:
        pdf.set_fill_color(255, 235, 235)
        pdf.set_draw_color(224, 82, 82)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_x(10)
        pdf.cell(190, 7, "  ⚠  CRITICAL FLAGS", ln=True, fill=True, border=1)
        pdf.set_font("Helvetica", "", 9)
        for flag in result.red_flags:
            clean_flag = re.sub(r"[^\x00-\x7F]+", "!", flag)
            pdf.set_x(14)
            pdf.multi_cell(186, 5, f"• {clean_flag}")
        pdf.ln(3)

    # ── Recommendations ─────────────────────────────────────────────────
    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 7, "Recommended Actions", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    for i, rec in enumerate(result.recommendations, 1):
        clean_rec = re.sub(r"[^\x00-\x7F]+", "", rec)
        clean_rec = re.sub(r"^\s*[🔴💡⚠️]\s*", "", clean_rec).strip()
        pdf.set_x(10)
        pdf.multi_cell(190, 5, f"{i}. {clean_rec}")
        pdf.ln(1)

    # ── Footer ───────────────────────────────────────────────────────────
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(120, 120, 120)
    pdf.cell(0, 5,
             f"bpdisdet v1.0  |  SDG-3 Mental Health Screening  |  "
             f"Session {result.session_id}  |  {datetime.now().strftime('%Y-%m-%d')}",
             align="C")

    return pdf.output()


def _draw_score_bar(pdf, label: str, score: float):
    """Draw a labelled progress bar for a score."""
    from fpdf import FPDF
    BAR_W = 100
    x = 10

    pdf.set_font("Helvetica", "", 10)
    pdf.set_x(x)
    pdf.cell(65, 6, label)

    # Colour gradient: green → orange → red
    if score < 33:
        r, g, b = 76, 175, 125
    elif score < 66:
        r, g, b = 224, 154, 47
    else:
        r, g, b = 224, 82, 82

    bar_y = pdf.get_y() + 1
    filled = int(BAR_W * score / 100)
    pdf.set_fill_color(230, 230, 230)
    pdf.rect(75, bar_y, BAR_W, 4, "F")
    pdf.set_fill_color(r, g, b)
    if filled > 0:
        pdf.rect(75, bar_y, filled, 4, "F")

    pdf.set_font("Helvetica", "B", 10)
    pdf.set_x(178)
    pdf.cell(22, 6, f"{score:.0f} / 100", ln=True)